FROM python:3.11-slim

WORKDIR /app

# Установка системных зависимостей для PostgreSQL
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Создание директории для логов
RUN mkdir -p /app/logs

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"] 