services:
  # PostgreSQL база данных
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: pyrus_db
      POSTGRES_USER: pyrus_user
      POSTGRES_PASSWORD: pyrus_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pyrus_user -d pyrus_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/.pytest_cache
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://pyrus_user:pyrus_password@db:5432/pyrus_db
      PYTHONUNBUFFERED: 1
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
        python -c 'from database import engine; from sqlalchemy import text; engine.connect().execute(text(\"SELECT 1\"))' &&
        python init_user.py &&
        uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      "

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8081:5173"
    environment:
      - VITE_BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    command: npm run dev -- --host 0.0.0.0

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8082:80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

volumes:
  postgres_data:

