# build stage
FROM node:lts-alpine as build-stage
WORKDIR /app

# Настройка npm для улучшенной работы с сетью
RUN npm config set fetch-retry-mintimeout 20000 && \
    npm config set fetch-retry-maxtimeout 120000 && \
    npm config set fetch-timeout 300000

COPY frontend/package*.json ./
RUN npm install --prefer-online --no-audit
COPY frontend/ .
RUN npm run build

# production stage
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"] 